# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  -group: cb_account

stages:
  - stage: Test
    jobs:
      - job: Codebeamer
        displayName: "Codebeamerupload"
        steps:
         - script:
            echo "Empty job."

            - task: codeBeamer@1
              inputs: 
                test_xml_folder:
                test_run_name:
                test_run_id:
                server_url:
                cb_user:
                cb_password:
                test_configuration_id:
                test_case_tracker_id:
                test_run_tracker_id:
