# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  -group: cb_account

stages:
  - stage: Test
    jobs:
      - job: Codebeamer
        displayName: "Codebeamerupload"
        steps:
         - script:
            echo "Empty job."

            - task: codeBeamer@1
              inputs: 
                test_xml_folder: 'example
/test_results'
                test_run_name: '$(Build.DefinitionName) $(Build.Reason)'
                test_run_id: '$(Build.BuildId)'
                server_url: 'http://192.168.10.90:8083/cb/login.spr'
                cb_user:
                cb_password:
                test_configuration_id:
                test_case_tracker_id:
                test_run_tracker_id:
